import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar/Sidebar";
import SearchBar from "@/components/searchbar/search";

// const roboto = Roboto({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="bg-white">
        <div className="flex h-full w-full">
          <SideBar />
          <div id="page">
            <SearchBar/> {children}</div>
        </div>
      </body>
    </html>
  );
}
